version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/baronfung/order
    expose:
      - "8080"
    ports:
      - 8080:8080
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - "3306:33066"
    command: --init-file /var/lib/mysql/init.sql    
    volumes:
      - /home/code/data/golang-mysql/:/var/lib/mysql/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
